// Package version reports the tailmix and embedded Tailscale versions.
package version

import (
	_ "embed"
	"fmt"
	"runtime/debug"
	"strings"

	"golang.org/x/mod/semver"
	tsversion "tailscale.com/version"
)

//go:embed VERSION.txt
var versionDotTxt string

// These stamps are set by packaged builds using linker flags generated by
// cmd/mkversion. Plain Go builds leave them empty and use VCS build info.
var (
	longStamp      string
	shortStamp     string
	gitCommitStamp string
)

// Meta describes the versions embedded in the current tailmix binary.
type Meta struct {
	Short            string `json:"short"`
	Long             string `json:"long"`
	GitCommit        string `json:"gitCommit,omitempty"`
	GitDirty         bool   `json:"gitDirty,omitempty"`
	TailscaleVersion string `json:"tailscaleVersion"`
}

// GetMeta returns the versions embedded in the current tailmix binary.
func GetMeta() Meta {
	info, _ := debug.ReadBuildInfo()
	return metaFromBuildInfo(info, tailscaleVersionFromBuildInfo(info), buildStamps{
		short:  shortStamp,
		long:   longStamp,
		commit: gitCommitStamp,
	})
}

type buildStamps struct {
	short  string
	long   string
	commit string
}

func tailscaleVersionFromBuildInfo(info *debug.BuildInfo) string {
	if info != nil {
		for _, dependency := range info.Deps {
			if dependency.Path != "tailscale.com" {
				continue
			}
			if dependency.Replace != nil {
				dependency = dependency.Replace
			}
			if dependency.Version != "" && dependency.Version != "(devel)" {
				return dependency.Version
			}
			break
		}
	}
	return "v" + tsversion.GetMeta().MajorMinorPatch
}

func metaFromBuildInfo(info *debug.BuildInfo, tailscaleVersion string, stamps buildStamps) Meta {
	meta := Meta{
		TailscaleVersion: tailscaleVersion,
	}
	var commitTime string
	if info != nil {
		for _, setting := range info.Settings {
			switch setting.Key {
			case "vcs.revision":
				meta.GitCommit = setting.Value
			case "vcs.time":
				commitTime = setting.Value
			case "vcs.modified":
				meta.GitDirty = setting.Value == "true"
			}
		}
	}
	if stamps.commit != "" {
		meta.GitCommit = stamps.commit
	}
	if stamps.short != "" {
		meta.Short = stamps.short
	} else {
		meta.Short = developmentVersion(commitTime)
	}
	if stamps.long != "" {
		meta.Long = stamps.long
	} else if meta.GitCommit == "" || len(commitTime) < len("yyyy-mm-dd") {
		meta.Long = "v" + strings.TrimSpace(versionDotTxt) + "-ERR-BuildInfo"
	} else {
		commit := meta.GitCommit
		if len(commit) > 9 {
			commit = commit[:9]
		}
		meta.Long = fmt.Sprintf("%s-t%s", developmentVersion(commitTime), commit)
		if meta.GitDirty {
			meta.Long += "-dirty"
		}
	}
	return meta
}

func developmentVersion(commitTime string) string {
	base := "v" + strings.TrimSpace(versionDotTxt)
	separator := "-dev."
	if semver.Prerelease(base) != "" {
		separator = "."
	}
	if len(commitTime) < len("yyyy-mm-dd") {
		return base + separator + "ERR-BuildInfo"
	}
	date := strings.ReplaceAll(commitTime[:len("yyyy-mm-dd")], "-", "")
	return base + separator + date
}

// Format returns meta as a human-readable version report for component.
func (meta Meta) Format(component string) string {
	var report strings.Builder
	fmt.Fprintf(&report, "%s %s\n", component, meta.Short)
	if meta.GitCommit != "" {
		fmt.Fprintf(&report, "  commit: %s", meta.GitCommit)
		if meta.GitDirty {
			report.WriteString("-dirty")
		}
		report.WriteByte('\n')
	}
	fmt.Fprintf(&report, "  long version: %s\n", meta.Long)
	fmt.Fprintf(&report, "  tailscale: %s", meta.TailscaleVersion)
	return report.String()
}

// String returns meta as a human-readable tailmix version report.
func (meta Meta) String() string {
	return meta.Format("tailmix")
}

// String returns the human-readable version report for the current binary.
func String() string {
	return GetMeta().String()
}
