#!/bin/sh

set -eu

root=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
version=v1.6.0
output="$root/licenses/tailmix.md"
freetype_version=v0.0.0-20170609003504-e2365dfdc4a0

case ${1:-check} in
	check|update) mode=${1:-check} ;;
	*)
		echo "usage: $0 [check|update]" >&2
		exit 2
		;;
esac

tmp=$(mktemp -d "${TMPDIR:-/tmp}/tailmix-licenses.XXXXXX")
trap 'rm -rf "$tmp"' EXIT HUP INT TERM
mkdir "$tmp/bin"

GOBIN="$tmp/bin" go install "github.com/google/go-licenses@$version"
go_licenses="$tmp/bin/go-licenses"

actual_freetype_version=$(go list -m -f '{{.Version}}' github.com/golang/freetype)
if [ "$actual_freetype_version" != "$freetype_version" ]; then
	echo "github.com/golang/freetype changed from the reviewed $freetype_version to $actual_freetype_version" >&2
	echo "review its license and update the explicit exception in scripts/licenses.sh" >&2
	exit 1
fi

check_target() {
	goos=$1
	goarch=$2
	env GOOS="$goos" GOARCH="$goarch" "$go_licenses" check \
		./cmd/tailmix ./cmd/tailmixd \
		--ignore github.com/maisem/tailmix \
		--ignore github.com/golang/freetype
}

report_target() {
	goos=$1
	goarch=$2
	destination=$3
	env GOOS="$goos" GOARCH="$goarch" "$go_licenses" report \
		./cmd/tailmix ./cmd/tailmixd \
		--ignore github.com/maisem/tailmix \
		--template "$root/licenses/report.tmpl" >"$destination"
}

cd "$root"
check_target darwin arm64
check_target linux amd64
report_target darwin arm64 "$tmp/darwin.md"
report_target linux amd64 "$tmp/linux.md"

generated="$tmp/tailmix.md"
{
	printf '%s\n\n' '# tailmix binary dependencies'
	printf '%s\n' 'This file is generated by `make licenses` using'
	printf '%s\n' "[go-licenses $version](https://github.com/google/go-licenses/tree/$version)."
	printf '%s\n\n' 'Do not edit it by hand.'
	printf '%s\n' 'The report covers the supported tailmix and tailmixd build targets. The same'
	printf '%s\n\n' 'package can appear more than once when it contains multiple license files.'
	printf '%s\n\n' '## Darwin (arm64)'
	cat "$tmp/darwin.md"
	printf '\n%s\n\n' '## Linux (amd64)'
	cat "$tmp/linux.md"
} >"$generated"

if [ "$mode" = update ]; then
	install -m 0644 "$generated" "$output"
	exit 0
fi

if ! cmp -s "$generated" "$output"; then
	echo "licenses/tailmix.md is stale; run 'make licenses'" >&2
	diff -u "$output" "$generated" || true
	exit 1
fi
